[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
build_flags =
  -D USBCON
  -D HAL_PCD_MODULE_ENABLED
  -D USBD_USE_HID_COMPOSITE
  -D CUSTOM_USBD_PID=0x5750
  -D USBD_SELF_POWERED=0
  -D USBD_MAX_POWER=100
  -D USB_PRODUCT_STRING=\"Nucleo_F446RE_Custom_HID\"
  -D USBD_CUSTOM_HID_REPORT_DESC_SIZE=27
  -D CUSTOM_HID_EPIN_SIZE=2
  -D CUSTOM_HID_EPOUT_SIZE=2
  -D USBD_CUSTOMHID_OUTREPORT_BUF_SIZE=2
  -IC:/Users/edja/.platformio/packages/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc
  -IC:/Users/edja/.platformio/packages/framework-arduinoststm32/system/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src
